# 2.1 数据操作
- **目录**
  - 2.1.1 入门
  - 2.1.2 运算符
  - 2.1.3 广播机制
  - 2.1.4 索引和切片
  - 2.1.5 节省内存
  - 2.1.6 转换为其他Python对象
  - 2.1.7 维度重新排列与轴变换

- $n$维数组，也称为**张量（tensor）**。
  - 在PyTorch和TensorFlow中为`Tensor`，二者都与Numpy的`ndarray`类似。

  - GPU很好地支持PyTorch和TensorFlow张量的加速计算，而NumPy仅支持CPU计算；

- 张量类支持<b>自动微分。
  - 张量类的自动微分功能非常有利于深度学习建模。

## 2.1.1 入门

本教程所使用的基本数值计算工具。

- **导入`torch`，代码中使用`torch`而不是`pytorch`。**


In [18]:
import torch
torch.__version__

'2.1.2+cu121'

- **张量表示由一个数值组成的数组，这个数组可能有多个维度**。
  - 具有一个轴的张量对应数学上的**向量（vector）**。
  - 具有两个轴的张量对应数学上的**矩阵（matrix）**。
  - 具有两个轴以上的张量没有特殊的数学名称。


- 使用 `arange` 创建一个行向量 `x`。
  - 默认创建的数据类型为整数，可指定创建类型为其他类型比如：浮点数。
  - 张量中的每个值都称为张量的 **元素（element）**。
  - 张量创建后，**默认将存储在机器的内存中，使用CPU计算。**
  - 可以通过参数指定存储在GPU中，并进行计算。

In [19]:
# arange函数创建维度为12的行向量 
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 可以通过张量的`shape`属性来访问张量（沿每个轴的长度）的**形状**


In [20]:
x.shape

torch.Size([12])

- 如果只想知道张量中元素的总数可以使用numel()。
- size函数得出张量的形状或尺寸，结果和shape属性一致。

In [21]:
x.numel(),x.shape,x.size() # shape属性与size函数的结果一致。注意：前者是张量属性；后者是pytorch函数

(12, torch.Size([12]), torch.Size([12]))

- **改变张量的形状：reshape函数**

In [22]:
# 张量x从形状为（12,）的行向量转换为形状为（3,4）的矩阵
X = x.reshape(3, 4)
X,X.shape,X.size() # shape属性与size函数的结果一致

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 torch.Size([3, 4]),
 torch.Size([3, 4]))

- **使用参数`-1`自动计算张量维度**
  - 可以用`x.reshape(-1,4)`或`x.reshape(3,-1)`来取代`x.reshape(3,4)`。
  - (-1, 4)：-1所在轴的维度为12/4 = 3，reshape后的形状为(3, 4)。
  - (3, -1)：-1所在轴的维度为12/3 = 4，reshape后的形状也是(3, 4)。

In [23]:
X1 = x.reshape(-1, 4)
X2 = x.reshape(3, -1)
X1.shape, X2.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

- **使用全0、全1、其他常量，或者从特定分布中随机采样的数字**来初始化矩阵。


In [24]:
# 创建一个形状为（2,3,4）的张量，其中所有元素都设置为0
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [25]:
# 创建一个形状为(2,3,4)的张量，其中所有元素都设置为1
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [26]:
# 通过从某个特定的概率分布中随机采样来得到张量中每个元素的值
# 每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样
torch.randn(3, 4)

tensor([[-0.8228, -0.5454,  0.0907, -0.7303],
        [ 0.7852, -0.9472, -0.4773,  1.1415],
        [-0.5561,  1.2983,  2.2317, -1.9276]])

- **通过提供包含数值的Python列表（或嵌套列表），来为深度学习模型张量的每个元素赋予确定值**。
  - 最外层的列表list对应于轴0（**垂直方向**，维度为3），内层的list对应于轴1（**水平方向**，维度为4）。
  - 轴的方向很重要，后面很多深度学习模型的张量计算过程都涉及到，要牢固掌握。


In [27]:
# 个人感觉此种直接生成张量的方法比TensorFlow更方便
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [28]:
torch.arange(1,25).reshape(2,3,4)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

- reshape函数的两种调用方式以及和numpy的reshape函数的比较

In [29]:
n = torch.arange(1,25)
n.reshape(2,3,4), torch.reshape(n,(2,3,4))

(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]),
 tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],
 
         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]))

In [46]:
import numpy as np
t = np.arange(1,25)
# 二者得出的结果一样，但是要注意t.reshape是就地修改t的形状，np.reshape是返回一个新对象
t.reshape(2,3,4),np.reshape(t,(2,3,4))

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]),
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]))

## 2.1.2 运算符

- 最简单且最有用的操作是**按元素（elementwise）** 运算。
  - 按元素运算将二元运算符应用于两个数组中的每对位置对应的元素。
  - 可以基于任何从标量到标量的函数来创建按元素函数。
  - 常见的标准算术运算符 **（`+`、`-`、`*`、`/`和`**`）** 都可以被升级为按元素运算。
  - 按元素操作**一般**要求两个张量的形状相同。
  - 某些情况下可以通过**广播机制**对两个形状不同的张量进行按元素运算。

In [33]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [34]:
# 对自然对数的底数e求x次幂
torch.exp(x) # 也是按元素计算

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

- **多个张量的连结（concatenate）运算**
  - 多个张量的端对端地叠起来形成一个更大的张量。
  - 提供张量列表，并指定沿哪个轴连结。

- **示例：**
  - 第一个输出张量的轴-0长度（$6$）是两个输入张量轴-0长度的总和（$3 + 3$）；
  - 第二个输出张量的轴-1长度（$8$）是两个输入张量轴-1长度的总和（$4 + 4$）。


In [35]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# 分别沿行（轴-0，垂直方向）和按列（轴-1，水平方向）连结两个矩阵
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

- **通过逻辑运算符构建二元张量**
- 以`X == Y`为例：
  - 对于每个位置，如果`X`和`Y`在该位置相等，则新张量中相应项的值为`True`或`1`。
  - 否则，该位置为`False`或`0`。


In [36]:
# 按元素进行逻辑运算，结果是布尔值
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [37]:
True == 1, False == 0, True == 0, False == 1

(True, True, False, False)

In [38]:
# 很诡异的行为：True和1类型不同，但是==运算表明二者完全相等
type(True), type(1) 

(bool, int)

- **对张量中的所有元素进行求和**
  - `sum`函数如果不带参数，则对所有元素求和。
  - 指定`dim`或`axis`参数则表示的对哪个轴或方向上求和。
  - 个人感觉，Pytorch里使用`dim`作为参数名较多，Numpy里一般使用`axis`。


In [39]:
# 注意0和1表示求和的维度或方向，
# “方向”理解起来要更直观一点。
X.sum(),X.sum(dim = 0),X.sum(axis = 1)

(tensor(66.), tensor([12., 15., 18., 21.]), tensor([ 6., 22., 38.]))

In [40]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

- **小测试**：现有一个3维张量，调用sum函数，当设置dim等于0,1,2时，各自的计算结果是什么？
  

In [41]:
X_3 = torch.arange(1,25).reshape((2,3,4))
X_3

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

In [42]:
# 思考下列张量运算
X_3.sum(dim=0),X_3.sum(dim=1),X_3.sum(dim=2)

(tensor([[14, 16, 18, 20],
         [22, 24, 26, 28],
         [30, 32, 34, 36]]),
 tensor([[15, 18, 21, 24],
         [51, 54, 57, 60]]),
 tensor([[10, 26, 42],
         [58, 74, 90]]))

## 2.1.3 广播机制
- 即使形状不同，仍可通过**广播机制（broadcasting mechanism）来执行按元素操作**:
  - 首先，通过适当**复制元素**来**扩展**一个或两个数组，以便在转换之后，两个张量具有**相同**的形状。
  - 其次，对生成的数组执行按元素操作。

- **示例：**
  - `x1`的形状为${(4, )}$, `y1`的形状为${(3, 4)}$。
  - `x1`会在垂直方向进行广播，变成${[[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4]]}$。
  - 广播后的`x1`与`y1`按元素相乘。
  - `x2`的形状为${(3, 1)}$，然后进行水平方向广播，变成${[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]]}$,然后与`y1`按元素相乘。

In [78]:
#x1 = torch.tensor([1,2,3,4]) # 形状为(4,)，也可以进行纵向传播
x1 = torch.tensor([1,2,3,4]).reshape(1, 4) # 形状(1, 4)
x2 = torch.tensor([1,2,3]).reshape(3, -1) # 形状(3, 1)
y1 = torch.arange(0,12).reshape(3, 4)

x1, x2, y1, x1.shape, x2.shape, y1.shape

(tensor([[1, 2, 3, 4]]),
 tensor([[1],
         [2],
         [3]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 torch.Size([1, 4]),
 torch.Size([3, 1]),
 torch.Size([3, 4]))

In [79]:
# 广播后按元素相乘
x1*y1, x2*y1

(tensor([[ 0,  2,  6, 12],
         [ 4, 10, 18, 28],
         [ 8, 18, 30, 44]]),
 tensor([[ 0,  1,  2,  3],
         [ 8, 10, 12, 14],
         [24, 27, 30, 33]]))

- **示例：**  
  - `a`和`b`分别是$3\times1$和$1\times2$矩阵。
  - 矩阵`a`将复制列(按照`b`的列数复制)，矩阵`b`将复制行（按照`a`的行数复制）。
  - 两个矩阵**广播**为一个更大的$3\times2$矩阵。
  - 再按元素相加。


In [80]:
# 另一个例子
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [81]:
# 将a, b各自广播成(3, 2)的形状后按元素相加求和
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [82]:
# a, b张量被广播过程
# cat函数的dim和axis似乎为同一个参数，功能相同
a1 = torch.cat([b,b,b],axis = 0) # axis = 0表示垂直方向广播
b1 = torch.cat([a,a],dim = 1)  # axis = 1表示水平方向广播
a1, b1, a1 + b1

(tensor([[0, 1],
         [0, 1],
         [0, 1]]),
 tensor([[0, 0],
         [1, 1],
         [2, 2]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

- **小测试：** a1的形状为(3,4,2), b1的形状为(4,1)，a1+b1运算如何广播？

In [47]:
a1 = torch.arange(1,25).reshape(3,4,2)
b1 = torch.arange(4,8).reshape(4,1)
a1,b1

(tensor([[[ 1,  2],
          [ 3,  4],
          [ 5,  6],
          [ 7,  8]],
 
         [[ 9, 10],
          [11, 12],
          [13, 14],
          [15, 16]],
 
         [[17, 18],
          [19, 20],
          [21, 22],
          [23, 24]]]),
 tensor([[4],
         [5],
         [6],
         [7]]))

In [48]:
# (3,4,2)形状的张量与(4,1)形状的张量进行运算如何广播？
a1+b1

tensor([[[ 5,  6],
         [ 8,  9],
         [11, 12],
         [14, 15]],

        [[13, 14],
         [16, 17],
         [19, 20],
         [22, 23]],

        [[21, 22],
         [24, 25],
         [27, 28],
         [30, 31]]])

## 2.1.4 索引和切片
与Python的数组或list切片以及Numpy的切片机制基本一致：
  - 第一个元素的索引是0，最后一个元素索引是-1；
  - 指定范围以包含第一个元素和最后一个元素之前的元素。




In [49]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [50]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

- **通过指定索引来将元素写入矩阵**


In [51]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

- **索引指定多个元素，赋相同值**

In [52]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5 节省内存

- **运行一些操作可能导致内存分配，从而增加内存消耗**。
- 解决方法之一是使用**就地操作**(In-place operations) 。

In [53]:
# 用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的张量。
Y = 10
before = id(Y)
Y = Y + X
# Y的内存地址发生变化，即分配了新的内存
before, id(Y), id(Y) == before

(140706189468744, 1322622047664, False)

- 注意：
  - 尽量避免不必要地分配内存。在机器学习中，参数的size动辄数百兆，而且往往更新频繁，而且每次更新都是全部更新(dropout机制除外)。
  - 通常情况下希望就地执行这些更新，比如深度学习模型**权重**的更新基本上都是就地操作。
  - 即便不就地更新，仍有引用指向参数的原内存位置，这就会导致引用参数旧值的情况出现，这种情况不一定是用户希望的。


In [54]:
# zeros_like生成一个与Y形状相同的张量，元素值皆为0
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))

# Z[:]注意切片方式可以保证就地操作
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1322644398800
id(Z): 1322644398800


- `X[:] = X + Y`或`X += Y`可以减少操作的内存开销
  - 前提：没有其他程序需引用X的原值


In [55]:
before = id(X)
# +=操作符也是就地操作
X += Y
id(X) == before

True

In [56]:
# 此操作就不是就地操作
X = X + Y 
id(X), before

(1322622050352, 1322644705680)

## 2.1.6 转换为其他Python对象


- 张量和NumPy张量（`ndarray`）互换
- torch张量和numpy数组将共享底层内存，因此就地操作更改一个张量也会同时更改另一个张量。
- 要将**大小为1的张量**转换为Python标量，可调用`item`函数或Python的内置函数实现。

In [57]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [58]:
a = torch.tensor([3.5])
# 使用张量的item函数或python的float或int等内置函数
# 将单元素的张量转换成标量，此种操作在深度学习的编程中很常见
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 2.1.7 维度重新排列与轴变换

- 在卷积神经网络（Convolutional Neural Networks, CNNs）中，图像数据通常表示为多维张量。
- 这些张量的结构如下所示：
  - 通道优先 (Channel-first)：形状为 (C, H, W)。
  - 通道末尾 (Channel-last)：形状为(H, W, C)。
- C, H, W的意义如下：
  - C：通道数量，对于彩色图像，通常有 3 个通道（红、绿、蓝），而对于灰度图像则只有 1 个通道。
  - H：图像的高度，表示垂直方向上的像素数。
  - W：图像的宽度，表示水平方向上的像素数。  
- 不同的深度学习框架可能默认采用不同的表示方法：
  - PyTorch 默认使用通道优先表示法。
  - TensorFlow 默认使用通道末尾表示法。
  - matplotlib 默认使用通道末尾表示法。

In [59]:
# 模拟图像数据，通道维在第3维(2轴)，因此需要将之重排到第1维（0轴）
imag = torch.arange(0, 60).reshape(5,4,3)
imag.shape

torch.Size([5, 4, 3])

-----------
- **说明：permute函数**
  - permute函数3个参数，代表期望的维度排序。
  - 比如下例中：
    - 将原来的2轴（第3维）变换到0轴（第1维）。
    - 将原来的0轴重排到1轴，1轴重排到2轴。
  - permute函数参数是一个元组：
    - 元组索引代表变换后的轴顺序，比如本例中0,1,2索引分别代表新张量的0,1,2轴。
    - 元组相应索引对应的元素值表示将原张量的哪个维度重排到此索引所代表的新张量的维度，(2,0,1)中的2就是将原张量的2轴重排到新张量的0轴。

In [60]:
# 重排后的维度
imag2 = imag.permute((2,0,1))
imag2.shape

torch.Size([3, 5, 4])

In [61]:
imag, imag2

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8],
          [ 9, 10, 11]],
 
         [[12, 13, 14],
          [15, 16, 17],
          [18, 19, 20],
          [21, 22, 23]],
 
         [[24, 25, 26],
          [27, 28, 29],
          [30, 31, 32],
          [33, 34, 35]],
 
         [[36, 37, 38],
          [39, 40, 41],
          [42, 43, 44],
          [45, 46, 47]],
 
         [[48, 49, 50],
          [51, 52, 53],
          [54, 55, 56],
          [57, 58, 59]]]),
 tensor([[[ 0,  3,  6,  9],
          [12, 15, 18, 21],
          [24, 27, 30, 33],
          [36, 39, 42, 45],
          [48, 51, 54, 57]],
 
         [[ 1,  4,  7, 10],
          [13, 16, 19, 22],
          [25, 28, 31, 34],
          [37, 40, 43, 46],
          [49, 52, 55, 58]],
 
         [[ 2,  5,  8, 11],
          [14, 17, 20, 23],
          [26, 29, 32, 35],
          [38, 41, 44, 47],
          [50, 53, 56, 59]]]))

- 也可以通过`swapdims`函数实现：
  - 首先将`imag`的0轴与2轴互换，结果为`imag3`新变量。
  - 然后再将`imag3`的1轴和2轴互换，结果`imag4`张量和`imag2`完全一致。

In [62]:
# 此方法稍微麻烦一点
imag3 = torch.swapdims(imag, 0, 2)
imag4 = torch.swapdims(imag3, 1, 2)
imag4.shape, imag4

(torch.Size([3, 5, 4]),
 tensor([[[ 0,  3,  6,  9],
          [12, 15, 18, 21],
          [24, 27, 30, 33],
          [36, 39, 42, 45],
          [48, 51, 54, 57]],
 
         [[ 1,  4,  7, 10],
          [13, 16, 19, 22],
          [25, 28, 31, 34],
          [37, 40, 43, 46],
          [49, 52, 55, 58]],
 
         [[ 2,  5,  8, 11],
          [14, 17, 20, 23],
          [26, 29, 32, 35],
          [38, 41, 44, 47],
          [50, 53, 56, 59]]]))

In [63]:
# swapaxes与swapdims函数功能一致
imag5 = torch.swapaxes(imag, 0, 2)
imag6 = torch.swapaxes(imag5, 1, 2)
imag6.shape, imag6

(torch.Size([3, 5, 4]),
 tensor([[[ 0,  3,  6,  9],
          [12, 15, 18, 21],
          [24, 27, 30, 33],
          [36, 39, 42, 45],
          [48, 51, 54, 57]],
 
         [[ 1,  4,  7, 10],
          [13, 16, 19, 22],
          [25, 28, 31, 34],
          [37, 40, 43, 46],
          [49, 52, 55, 58]],
 
         [[ 2,  5,  8, 11],
          [14, 17, 20, 23],
          [26, 29, 32, 35],
          [38, 41, 44, 47],
          [50, 53, 56, 59]]]))

-------

## 小结

* 深度学习存储和操作数据的主要接口是张量（$n$维数组）。
* 张量提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换为其他Python对象。
